travis:
  secure:
    BINSTAR_TOKEN: LMVpGApyG/KrQBv6d6DJpRFv7YtkAnm15sVhmcuqfSaok5kUIl6FvhvaYtTHmUf3kzTeRH5/6ZXcPqE1i9IHa1LNC4FW6eVSwAmgsgxYx9dNEWQyKlGHU/2xMyrQaskjh121IlXIwFOqDdj0hYrAnnOjmz7fDQSyGZyFEushRNoiT4pCdFLWastChIIrz/O6kLG5Kekv6OHzTieWptViheq4f+WFq+0hDsA4LfGvHZAXNGwSohBUFijncqMUwKJiWl5j0neqtQyf577iMymvsI/SfJdUR7PPCiivuBKjbwX0SzEKtwZ0oqvzbN4yaBqm+jNoXIvX29aSgcGwmrfbxExGtsBN2Gnj1AllEvmkrMOehrWRfw4UuxwyWEP/5dr1KQXpIs/p6Poa6vEfXhfTnPhTYmD/2zR3Xag9RX0KUS5x6lAM099mSyGmBlzXVkBmCVfLd5Yt8cLLAuT/R2f2OCNRz8WpElit9zvjs9wAtv7cJjHCctJeA+H1C3LTM6y1BjhS73rTyLxXMJ/ADIm9lITGO66TENtvqZfS6rjLzhnv+VKiulOBrL3BDvSrletTvyLeuVV/Kf7VklR8qXkx2k0CVwv81NHl1wHDo3gbIqFI0IErMggDLswL3FD65cSJuo5R04PoBe6tzrTeyxd+qj3yr7TbsCA2aN3rdldIKc0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
