travis:
  secure:
    BINSTAR_TOKEN: FRseCQg161z3ks9hL3l0Por+wIsPSro5gHrSvPE4QFKbP/g8wB2vDy++uSuYXPFsCONXAquhHB+e+8/1mlJCpMnBC7LBpJjEBnrNHlS+JaI3oytIx8duW27CV1zU8n8kbtOsERgmYpBHsD27vZVG6jTdErxBESBfxENpG7sWzUf5xrziRWhKkS1IzTCjHNjSw/obp/SxmWBu0UfbBRNaBuDjA/axRTYNg9rKdkOm4FLALCAtpjMKD+J6qFaJHT0HnjmEvTPCf2gtN7OCvtXV9zMDNzcJj7vCUaILpBCvK+MurzGujDQzIoOjFsDGvuhIXKQNkJkZywjWl98+FpAhZ37kPzgUEhPlqp0AjXzQEpDUbB9KA55hFSk+iyEiJAPd3hTFPQeX+xOaSclOF2pnsbeGK+8h6G3xy/UxL31ZcFD+KvNTb5hy48R7U6MLck3DWS7pQruadSwQw6uxntwTSiieZzcqrErBxULoucudMn3sBj0jF1ITEq6qaaLXGVIN7GY7AxV7lus/t2ibisMYZTHnBK5q7CEFL+QSnk2GrjAC+jF5eN9tNpaE5o5eCqcM80iu2njkLlH+JnaMYEJbdLWI6lAIo6Mqb+awCAdm1VispPU7t43BqMPbx2CqDCiHXyDdVZ8G4YVM1ncU3EoXEigpk31qYlBItiDSSv/CKZY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
